2024-06-14 09:30:33,551 - __main__ - INFO - Processing scenario 982
2024-06-14 09:30:40,390 - __main__ - INFO - Processing archive 1/5 for scenario 982
2024-06-14 09:30:40,401 - __main__ - DEBUG - Processed NFE 0 for archive 1/5 in scenario 982
2024-06-14 11:10:47,083 - __main__ - INFO - Processing scenario 982
2024-06-14 11:10:53,949 - __main__ - INFO - Processing archive 1/5 for scenario 982
2024-06-14 11:10:53,958 - __main__ - DEBUG - Processed NFE 0 for archive 1/5 in scenario 982
2024-06-14 11:29:11,330 - __main__ - INFO - Processing scenario 982
2024-06-14 11:29:18,697 - __main__ - INFO - Processing archive 1/5 for scenario 982
2024-06-14 11:29:18,709 - __main__ - DEBUG - Processed NFE 0 (1/7) for archive 1/5 in scenario 982
2024-06-14 13:28:31,885 - __main__ - INFO - Processing scenario 982
2024-06-14 13:28:34,735 - __main__ - INFO - Processing archive 1/5 for scenario 982
2024-06-14 13:28:34,735 - __main__ - DEBUG - Processed NFE 0 (1/7) for archive 1/5 in scenario 982
2024-06-14 13:32:58,177 - __main__ - INFO - Processing scenario 982
2024-06-14 13:33:01,250 - __main__ - INFO - Processing archive 1/5 for scenario 982
2024-06-14 13:33:01,250 - __main__ - DEBUG - Processed NFE 0 (1/7) for archive 1/5 in scenario 982 in 0.00s
2024-06-14 13:36:57,239 - __main__ - INFO - Processing scenario 982
2024-06-14 13:37:12,954 - __main__ - INFO - Processing scenario 982
2024-06-14 13:38:39,932 - __main__ - INFO - Processing scenario 982
2024-06-14 13:38:40,041 - __main__ - ERROR - Error processing future result for scenario 982: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "C:\Users\prima\AppData\Local\Temp\ipykernel_22744\411351657.py", line 96, in <module>
    convergence_metrics[scenario].extend(future.result())
                                         ^^^^^^^^^^^^^^^
  File "C:\Users\prima\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prima\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
2024-06-14 13:38:40,043 - __main__ - INFO - Processing scenario 632
2024-06-14 13:38:40,173 - __main__ - ERROR - Error processing future result for scenario 632: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "C:\Users\prima\AppData\Local\Temp\ipykernel_22744\411351657.py", line 96, in <module>
    convergence_metrics[scenario].extend(future.result())
                                         ^^^^^^^^^^^^^^^
  File "C:\Users\prima\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prima\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
2024-06-14 13:38:40,173 - __main__ - INFO - Processing scenario 248
2024-06-14 13:38:40,280 - __main__ - ERROR - Error processing future result for scenario 248: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "C:\Users\prima\AppData\Local\Temp\ipykernel_22744\411351657.py", line 96, in <module>
    convergence_metrics[scenario].extend(future.result())
                                         ^^^^^^^^^^^^^^^
  File "C:\Users\prima\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prima\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
2024-06-14 13:38:40,280 - __main__ - INFO - Processing scenario 541
2024-06-14 13:38:40,385 - __main__ - ERROR - Error processing future result for scenario 541: A process in the process pool was terminated abruptly while the future was running or pending.
Traceback (most recent call last):
  File "C:\Users\prima\AppData\Local\Temp\ipykernel_22744\411351657.py", line 96, in <module>
    convergence_metrics[scenario].extend(future.result())
                                         ^^^^^^^^^^^^^^^
  File "C:\Users\prima\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 449, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\prima\AppData\Local\Programs\Python\Python312\Lib\concurrent\futures\_base.py", line 401, in __get_result
    raise self._exception
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
2024-06-14 13:38:40,387 - __main__ - INFO - Completed processing all scenarios
2024-06-14 13:42:27,957 - __main__ - INFO - Processing scenario 982
2024-06-14 13:42:31,074 - __main__ - INFO - Processing archive 1/5 for scenario 982
2024-06-14 13:42:31,074 - __main__ - DEBUG - Processed NFE 0 (1/7) for archive 1/5 in scenario 982 in 0.00s
2024-06-14 13:45:34,445 - __main__ - INFO - Processing scenario 982
2024-06-14 13:45:34,446 - __main__ - INFO - Processing archive 1/5 for scenario 982
2024-06-14 13:45:34,449 - __main__ - INFO - Processing archive 2/5 for scenario 982
2024-06-14 13:45:34,449 - __main__ - INFO - Processing archive 3/5 for scenario 982
2024-06-14 13:45:34,484 - __main__ - INFO - Processing archive 4/5 for scenario 982
2024-06-14 13:45:34,553 - __main__ - INFO - Processing archive 5/5 for scenario 982
